services:
  - type: web
    name: finance-prognosis
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_DIR
        value: /var/data
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: finance-data
      mountPath: /var/data
      sizeGB: 1
